#! /bin/sh
CHECK_MODE=$(xrandr --current | grep Screen | grep 1920)
if [ -z "$CHECK_MODE" ]; then
	xrandr --output  HDMI-1 --mode 1920x1080 --scale 1x1 --output VGA-1 --same-as HDMI-1 --mode 1920x1080 --scale 1x1
else
	xrandr --output  VGA-1 --mode 1920x1080 --scale 1x1 --output HDMI-1 --mode 1920x1080 --scale 1x1 --left-of VGA-1
fi